clear all
%   SYNTAX
%   E71
%   DESCRIPTION
%   This module programs Dodd's analytical solution for eddy currents
%   generated by any number of arbitrarily-oriented horizontal loops and
%   outputs contour plot of eddy current density in the xz- and yz-planes
%   Dodd CV, Deeds WE, Analytical solutions to eddy-current probe-coil
%   problems, J. Appl. Phys., 1968, vol. 39, pp. 2829–38. 
%    
%   Low-Frequency Electromagnetic Modeling for Electrical and Biological
%   Systems Using MATLAB, Sergey N. Makarov, Gregory M. Noetscher, and Ara
%   Nazarian, Wiley, New York, 2105, 1st ed.

%%   Define static EM parameters
eps0        = 8.85418782e-012;                      %   Dielectric permittivity of vacuum(~air) F/m
mu0         = 1.25663706e-006;                      %   Magnetic permeability of vacuum(~air) H/m
c0          = 1/sqrt(eps0*mu0);                     %   Speed of light in vacuum(~air) m/s        
eta0        = sqrt(mu0/eps0);                       %   Vacuum/air 
sigma       = 1.0;                                  %   Medium conductivity, S/m

%%   Define domain size and grid size
%   (upper half is for air; lower half is for conductor)
sizex = 0.15; 
sizey = 0.15;
sizez = 0.1;
N = 100;
x = linspace(-sizex/2, +sizex/2, N);
y = linspace(-sizey/2, +sizey/2, N);
z = linspace(-sizez/2, +sizez/2, N);

%   Loop geometry parameters:
%  any number of horizontal coils defined by r0(:), x0(:), y0(:) z0(:)
%  r0 - radii, m
%  x0 - x-positions, m
%  y0 - y-positions, m
%  z0 - z-positions above the conducting boundary, m
%  I0 - currents in A, directional

%%   Case #1 (Example 11.3 and Fig. 11.9)
% r0(1) = +0.02;      
% x0(1) = +0.00;      
% y0(1) = 0;          
% z0(1) = 0.01;      
% %   Loop current parameters:
% I0(1) = +1e3;                   %   Amplitudes/directions of coil currents(+/-), A
% f               = 10e3;         %   Operation frequency, Hz
% omega           = 2*pi*f;       %   Angular frequency, rad/sec

%%   Case #2 (Example 11.4 and Fig. 11.11)
r0(1) = +0.02;      r0(2) = +0.02;
x0(1) = -0.02;      x0(2) = +0.02;
y0(1) = 0;          y0(2) = 0;
z0(1) = 0.01;       z0(2) = 0.01;
%   Loop current parameters:
I0(1) = +1e3; I0(2) = -1e3;     %   Amplitudes/directions of coil currents(+/-), A
f               = 10e3;         %   Operation frequency, Hz
omega           = 2*pi*f;       %   Angular frequency, rad/sec

%%   Case #3 (A "quadrupole" from Fig. 11.19)
% r0(1) = +0.02;      r0(2) = +0.015;     r0(3) = +0.010;  
% r0(4) = +0.02;      r0(5) = +0.015;     r0(6) = +0.010;  
% r0(7) = +0.02;      r0(8) = +0.015;     r0(9) = +0.010;
% r0(10) = +0.02;     r0(11)= +0.015;     r0(12) = +0.010;
% 
% x0(1) = -0.02;      x0(2) = -0.02;      x0(3) = -0.02;
% x0(4) = +0.02;      x0(5) = +0.02;      x0(6) = +0.02;
% x0(7) = +0.02;      x0(8) = +0.02;      x0(9) = +0.02;
% x0(10) = -0.02;     x0(11) = -0.02;     x0(12) = -0.02;
% 
% y0(1) = +0.02;      y0(2) = +0.02;      y0(3) = +0.02;
% y0(4) = +0.02;      y0(5) = +0.02;      y0(6) = +0.02;
% y0(7) = -0.02;      y0(8) = -0.02;      y0(9) = -0.02;
% y0(10) = -0.02;     y0(11) = -0.02;     y0(12) = -0.02;
% 
% z0(1) = +0.01;      z0(2) = +0.015;     z0(3) = +0.020;  
% z0(4) = +0.01;      z0(5) = +0.015;     z0(6) = +0.020;  
% z0(7) = +0.01;      z0(8) = +0.015;     z0(9) = +0.020;
% z0(10) = +0.01;     z0(11)= +0.015;     z0(12) = +0.020;
% 
% %   Loop current parameters: Amplitudes/directions of coil currents(+/-), A
% I0(1) = +1e3;         I0(2) = +1e3;     I0(3) = +1e3;  
% I0(4) = -1e3;         I0(5) = -1e3;     I0(6) = -1e3;  
% I0(7) = +1e3;         I0(8) = +1e3;     I0(9) = +1e3;
% I0(10)= -1e3;         I0(11)= -1e3;     I0(12)= -1e3;
% 
% f               = 10e3;         %   Operation frequency, Hz
% omega           = 2*pi*f;       %   Angular frequency, rad/sec

%%   Case #4
% r0(1) = +0.02;      r0(2) = +0.02;
% x0(1) = +0.00;      x0(2) = +0.00;
% y0(1) = 0;          y0(2) = 0;
% z0(1) = 0.01;       z0(2) = 0.015;
% %   Loop current parameters:
% I0(1) = +1; I0(2) = j;     %   Amplitudes/directions of coil currents(+/-), A
% f               = 10e3;         %   Operation frequency, Hz
% omega           = 2*pi*f;       %   Angular frequency, rad/sec

%%   Major loop 
zprime = z(z<0);
M = length(r0); N = length(x); P = length(y); Q = length(zprime);
h = waitbar(0,'Please wait. Computing the solution');
eddyXZx = zeros(M, N, Q);   % Cartesian component
eddyXZy = zeros(M, N, Q);   % Cartesian component
eddyYZx = zeros(M, P, Q);   % Cartesian component
eddyYZy = zeros(M, P, Q);   % Cartesian component

for m = 1:M
    waitbar((m-0.5)/M);  
    xprime = x - x0(m);
    yprime = y - y0(m);    
    %xz-plane (y = 0; yprime becomes y0)
    for n = 1:N
        for q = 1:Q
            radXZ = sqrt(xprime(n)^2 + y0(m)^2);
            depth = zprime(q);
            Jphi  = eddyatpoint(r0(m), z0(m), radXZ, depth, I0(m), mu0, omega, sigma);
            eddyXZx(m, n, q) = -y0(m)/radXZ*Jphi;
            eddyXZy(m, n, q) = +xprime(n)/radXZ*Jphi;
        end
    end
    %yz-plane (x = 0; xprime becomes x0)
    for p = 1:P
        for q = 1:Q
            radYZ = sqrt(x0(m)^2 + yprime(p)^2);
            depth = zprime(q);
            Jphi = eddyatpoint(r0(m), z0(m), radYZ, depth, I0(m), mu0, omega, sigma);
            eddyYZx(m, p, q) = -yprime(p)/radYZ*Jphi;
            eddyYZy(m, p, q) = +x0(m)/radYZ*Jphi;
        end
    end    
end
close(h); 

%   Summing the individual contributions (xz-plane)
eddyXZx      = abs(squeeze(sum(eddyXZx, 1)));
eddyXZy      = abs(squeeze(sum(eddyXZy, 1)));
eddyXZ       = sqrt(eddyXZx.^2 + eddyXZy.^2);
scaleXZ      = max(max(eddyXZ));
eddyXZ       = eddyXZ/scaleXZ;
[XZ, ZX]     = meshgrid(x, zprime);

%   Summing the individual contributions (yz-plane)
eddyYZx      = abs(squeeze(sum(eddyYZx, 1)));
eddyYZy      = abs(squeeze(sum(eddyYZy, 1)));
eddyYZ       = sqrt(eddyYZx.^2 + eddyYZy.^2);
scaleYZ      = max(max(eddyYZ));
eddyYZ       = eddyYZ/scaleYZ;
[YZ, ZY]     = meshgrid(y, zprime);

%%  Graphics: results in the xz-plane
%   Plot boxes 
f1 = figure;
box(sizex, sizey, sizez, 0, 0, 0, [1 1 1], 0, 1, 'k');                  %   box with air
box(sizex, sizey, sizez/2, 0, 0, -sizez/4, [1 0.75 0.65], 0.1, 1, 'k'); %   box with conductor
hold on;

%   Plot loops
L = 50;
phi = linspace(0, 2*pi, L);  %   parameteric circle/ellipse form     
Contour = zeros(L, 3);
for m = 1:M
    Contour(:, 1) = r0(m)*cos(phi) + x0(m);
    Contour(:, 2) = r0(m)*sin(phi) + y0(m);
    Contour(:, 3) = z0(m)*ones(size(phi));  
    line(Contour(:, 1), Contour(:, 2), Contour(:, 3), 'Color', 'b', 'LineWidth', 2.5);
end    

% Contour plot in the xz-plane
v             = [0.1:0.1:1];                        %   create contour plot levels
[CXZ, h1]     = contourf(XZ, ZX, eddyXZ', v);       %   create contour plot
colormap(summer);
rotate(get(h1, 'children'), [1 0 0], 90, [0 0 0]);

axis equal; axis tight; grid on; colorbar;
xlabel('x, m'); ylabel('y, m'); zlabel('z, m');
title(strcat('Normalized eddy current density in the xz-plane. Max dens.=', num2str(1e3*scaleXZ/1e4), 'mA/cm^2'));
view(-21, 16);

%%  Graphics: results in the yz-plane
%   Plot boxes 
f2 = figure;
box(sizex, sizey, sizez, 0, 0, 0, [1 1 1], 0, 1, 'k');                  %   box with air
box(sizex, sizey, sizez/2, 0, 0, -sizez/4, [1 0.75 0.65], 0.1, 1, 'k'); %   box with conductor
hold on;

%   Plot loops
L = 50;
phi = linspace(0, 2*pi, L);  %   parameteric circle/ellipse form     
Contour = zeros(L, 3);
for m = 1:M
    Contour(:, 1) = r0(m)*cos(phi) + x0(m);
    Contour(:, 2) = r0(m)*sin(phi) + y0(m);
    Contour(:, 3) = z0(m)*ones(size(phi));  
    line(Contour(:, 1), Contour(:, 2), Contour(:, 3), 'Color', 'b', 'LineWidth', 2.5);
end    

% Contour plot in the yz-plane
v             = [0.1:0.1:1];                        %   create contour plot levels
[CYZ, h2]     = contourf(YZ, ZY, eddyYZ', v);       %   create contour plot
colormap(summer);
rotate(get(h2, 'children'), [1 0 0], 90, [0 0 0]);
rotate(get(h2, 'children'), [0 0 1], 90, [0 0 0]);

axis equal; axis tight; grid on; colorbar;
xlabel('x, m'); ylabel('y, m'); zlabel('z, m');
title(strcat('Normalized eddy current density in the yz-plane. Max dens.=', num2str(1e3*scaleYZ/1e4), 'mA/cm^2'));
view(-21, 16);



